name: 'tar-and-upload-artifact'
description: 'tar-and-upload-artifact'
inputs:
  name:
    description: 'artifact name'
    required: false
    default: 'artifact.tar.gz'
  path:
    description: 'dir path'
    required: true
    default: '.'
  retention-days:
    description: 'retention-days'
    required: false
    default: 5
runs:
  using: "composite"
  steps:
    - run: tar -zcf ${{ inputs.name }} -C ${{ inputs.path }} .
      shell: bash
    - id: random-number-generator
      uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.name }}
          retention-days: ${{ inputs.retention-days }}
      shell: bash
    - run: rm -rf ${{ inputs.name }}
      shell: bash
