on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: hello
      uses: ./
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.hello.outputs.random-number }}
      shell: bash
